#ifndef DEFINES_H
#define DEFINES_H

// FILE: defines.h

#define RIGHT_R_PWM_PIN 14
#define RIGHT_L_PWM_PIN 13

#define LEFT_R_PWM_PIN 32
#define LEFT_L_PWM_PIN 33

#define CONTAINER_R_PWM_PIN 25
#define CONTAINER_L_PWM_PIN 26

#define CAMERA_RELAY_PIN 16
#define LAMP_RELAY_PIN 17

#define IR_1_PIN 18
#define IR_2_PIN 19

#define ACTIVE_CAMERA_VIRTUAL_PIN V0
#define FORWARD_VIRTUAL_PIN V1
#define BACKWARD_VIRTUAL_PIN V2
#define RIGHT_VIRTUAL_PIN V3
#define LEFT_VIRTUAL_PIN V4
#define MODE_VIRTUAL_PIN V5
#define DROP_VIRTUAL_PIN V6
#define SPEED_VIRTUAL_PIN V7
#define STREAM_VIRTUAL_PIN V8
#define LAMP_VIRTUAL_PIN V9

#define FRONT_CAMERA_URL "http://192.168.100.31/"
#define BACK_CAMERA_URL "http://192.168.100.36/"

#define LOADING_SPEED 50

#endif // DEFINES_H